### ISSUE TITLE
🐛 [bug] `IndexDefect` in `exactFindInPattern()` procedure.

### ISSUE THREAD

**Issue by hitblast** [hitblast/avro.nim#1]
## Helpful References

Writing this function is a part of my attempt to fully migrate avro.py to Nim. Here's [an identical representation](https://github.com/hitblast/avro.py/blob/c86265ba3f5860fff287df971ae9ebff6becb6ac/avro/main.py#LL252C1-L273C6) of the `exactFindInPattern()` procedure in Python which works as intended.

## The Issue

While manually compiling the Nim file for the executable (for testing purposes) and then running it using the following command,
```bash
$ nim c src/avro.nim && ./src/avro
```

an `IndexDefect` error is thrown.
```bash
# error logs
/Users/hitblast/Developer/avro.nim/src/avro.nim(7) avro
/Users/hitblast/Developer/avro.nim/src/avropkg/main.nim(260) parse
/Users/hitblast/Developer/avro.nim/src/avropkg/main.nim(97) matchPatterns
/Users/hitblast/Developer/avro.nim/src/avropkg/main.nim(50) exactFindInPattern
/opt/homebrew/Cellar/nim/1.6.12/nim/lib/system.nim(2552) []
/opt/homebrew/Cellar/nim/1.6.12/nim/lib/system/fatal.nim(54) sysFatal
Error: unhandled exception: index 19 not in 0 .. 18 [IndexDefect]
```

Now it turns out that it could be a defect with the `exactFindInPattern()` function's comparison part, but I'm unsure about where it is. Maybe we need to slice the `fixed_text` variable differently?

```nim
proc exactFindInPattern(fixed_text: string, reversed: bool, cur: int = 0, patterns: seq[JsonNode]): seq[JsonNode] =
    ## Returns pattern items that match given text, cursor position and pattern.
    
    var list: seq[JsonNode] = @[]

    if reversed:
        list = collect:
            for p in patterns:
                let compare = p["replace"].getStr()

                if (
                    (cur + len(compare) <= len(fixed_text)) and 
                    (compare == fixed_text[cur..(cur + len(compare))])
                ):
                    p
    else:
        list = collect:
            for p in patterns:
                if hasKey(p, "find"):
                    let compare = p["find"].getStr()

                    if (
                        (cur + len(compare) <= len(fixed_text)) and
                        compare == fixed_text[cur..(cur + len(compare))]
                    ):
                        p

    return list
```

**Comment by furtidev** [comment]
Modifying line 50 to: `(compare == fixed_text[cur .. (cur + len(compare))-1])` seems not throw an error anymore.
But the output is: `ai aay a ai`

**Comment by hitblast** [comment]
> Modifying line 50 to: `(compare == fixed_text[cur .. (cur + len(compare))-1])` seems not throw an error anymore.
> But the output is: `ai aay a ai`

Well, that is a matter of concern. I guess we should have a recheck throughout the other functions.

**Comment by baseplate-admin** [comment]
seems like nim starts index at 1 instead of 0 like other languages. Thats why what @furtidev said is correct :)

**Comment by hitblast** [comment]
@baseplate-admin @furtidev Following the conversation, I've changed the default starting index from `0` to `1` and `1` to `2` respectively with the https://github.com/hitblast/avro.nim/commit/24eaf810ed7d388a0fae0bfbd34c14e7fc829f11 commit. However, the output is like this:

<img width="366" alt="Screenshot 2023-06-06 at 11 35 21 PM" src="https://github.com/hitblast/avro.nim/assets/67194380/cb6bf073-6e4d-4085-9e92-ea4d4d45c50a">

Would you like to have a comparison between the main scripts of both avro.py and avro.nim? I'm not sure what I did wrong here but the output is supposed to be "আমি বাংলায় গান গাই" as expected.

**Comment by baseplate-admin** [comment]
I fixed the error so it currently parses the text into `ami banglay gaan gai`. The index Defect error is fixed but it doesn't translate to bengali

**Comment by hitblast** [comment]
> I fixed the error so it currently parses the text into `ami banglay gaan gai`. The index Defect error is fixed but it doesn't translate to bengali.
> 
> ```powershell
> PS C:\Programming\avro.nim>  nim c src/avro.nim
> Hint: used config file 'C:\tools\Nim\nim-1.6.12\config\nim.cfg' [Conf]
> Hint: used config file 'C:\tools\Nim\nim-1.6.12\config\config.nims' [Conf]
> ..........................................................................................
> Hint:  [Link]
> Hint: gc: refc; opt: none (DEBUG BUILD, `-d:release` generates faster code)
> 51667 lines; 0.442s; 75.461MiB peakmem; proj: C:\Programming\avro.nim\src\avro.nim; out: C:\Programming\avro.nim\src\avro.exe [SuccessX]
> 
> PS C:\Programming\avro.nim\src> .\avro.exe
> ami banglay gan gai
> ```

Neat! I'll shortly accept your pull request. However, now that it doesn't do anything to the original input text, I wonder if something's going wrong in the part where we check for valid Unicode characters. Any thoughts?

**Comment by baseplate-admin** [comment]
```nim
    if reversed:
        list = collect:
            for p in patterns:
                let compare = p["replace"].getStr()

                if (
                    (cur + len(compare) + 1 <= len(fixed_text)) and 
                    (compare == fixed_text[cur + 1 .. (cur + len(compare) - 1)])
                ):
                    p
    else:
        list = collect:
            for p in patterns:
                if hasKey(p, "find"):
                    let compare = p["find"].getStr()

                    if (
                        (cur + len(compare) + 1 <= len(fixed_text)) and
                        compare == fixed_text[cur + 1 .. (cur + len(compare) - 1)]
                    ):
                        p

```

What is p doing here?

**Comment by hitblast** [comment]
@baseplate-admin The `p` variable represents a specific pattern. Notice the `for` loop?

**Comment by baseplate-admin** [comment]
is it being assigned to anything?

**Comment by hitblast** [comment]
> is it being assigned to anything?

@baseplate-admin The `collect:` macro is basically creating a list of `p` or patterns.

**Comment by hitblast** [comment]
@baseplate-admin I'm closing this issue and creating a separate discussion dedicated to solving the parsing problem.

**Comment by baseplate-admin** [comment]
Sure thing

**Comment by hitblast** [comment]
@baseplate-admin Well, have a look when you're free I guess. Tanim's also online now so hopefully he could give us some idea.

**Comment by baseplate-admin** [comment]
Will do surely. Currently a bit busy as i have to get coreproject up and running. But i am debugging this at my free time :)

**Comment by hitblast** [comment]
> Will do surely. Currently a bit busy as i have to get coreproject up and running. But i am debugging this at my free time :)

Thanks :D
